// Mock Data for Trading Platform Demo

export const MOCK_CUSTOMER_PORTFOLIO = {
  clientName: 'Acme Corp',
  totalVolume: '$12.5M',
  kycStatus: 'Verified',
  allocation: {
    crude_oil: 60,
    minerals: 40,
  },
  activeOrders: [
    {
      id: 'ORD-2025-001',
      commodity: 'Crude Oil (Brent)',
      volume: '5,000 bbls',
      destination: 'Rotterdam, NL',
      eta: '2025-06-15',
      status: 'In Transit',
      price: '$82.50/bbl',
    },
    {
      id: 'ORD-2025-002',
      commodity: 'Iron Ore (62% Fe)',
      volume: '50,000 MT',
      destination: 'Shanghai, CN',
      eta: '2025-07-20',
      status: 'Pending LC',
      price: '$145/MT',
    },
    {
      id: 'ORD-2025-003',
      commodity: 'Natural Gas',
      volume: '1,000 MMBtu',
      destination: 'Singapore, SG',
      eta: '2025-06-08',
      status: 'Confirmed',
      price: '$8.25/MMBtu',
    },
    {
      id: 'ORD-2025-004',
      commodity: 'Copper (Grade A)',
      volume: '250 MT',
      destination: 'London, UK',
      eta: '2025-06-22',
      status: 'Processing Docs',
      price: '$9,800/MT',
    },
    {
      id: 'ORD-2025-005',
      commodity: 'Coal (Thermal)',
      volume: '100,000 MT',
      destination: 'Mumbai, IN',
      eta: '2025-08-10',
      status: 'Quote Sent',
      price: '$125/MT',
    },
  ],
};

export const MOCK_CRM_LEADS = [
  {
    id: 'INQ-001',
    companyName: 'Global Energy Solutions',
    inquiryDate: '2025-06-01',
    commodityInterest: 'Crude Oil, Natural Gas',
    contactPerson: 'John Martinez',
    email: 'john@globalenergy.com',
    status: 'New Inquiry',
    volume: '10,000 bbls',
  },
  {
    id: 'INQ-002',
    companyName: 'Asian Metals Corp',
    inquiryDate: '2025-05-28',
    commodityInterest: 'Iron Ore, Copper',
    contactPerson: 'Li Chen',
    email: 'li.chen@asianmetals.com',
    status: 'KYC Review',
    volume: '75,000 MT',
  },
  {
    id: 'INQ-003',
    companyName: 'European Industrial Group',
    inquiryDate: '2025-05-25',
    commodityInterest: 'Coal, Minerals',
    contactPerson: 'Hans Mueller',
    email: 'hans@euindustrial.de',
    status: 'Quotation',
    volume: '50,000 MT',
  },
  {
    id: 'INQ-004',
    companyName: 'Pacific Trade Partners',
    inquiryDate: '2025-05-20',
    commodityInterest: 'Natural Gas',
    contactPerson: 'Sarah Wong',
    email: 'sarah@pacifictrade.sg',
    status: 'KYC Review',
    volume: '5,000 MMBtu',
  },
  {
    id: 'INQ-005',
    companyName: 'Middle East Resources',
    inquiryDate: '2025-05-15',
    commodityInterest: 'Crude Oil',
    contactPerson: 'Ahmed Al-Rashid',
    email: 'ahmed@meresources.ae',
    status: 'Deal Closed',
    volume: '20,000 bbls',
  },
  {
    id: 'INQ-006',
    companyName: 'Africa Commodities Ltd',
    inquiryDate: '2025-06-02',
    commodityInterest: 'Minerals, Copper',
    contactPerson: 'Amara Okafor',
    email: 'amara@africacommodities.ng',
    status: 'New Inquiry',
    volume: '30,000 MT',
  },
];

export const MOCK_ERP_LOGISTICS = [
  {
    shipmentId: 'SHIP-2025-001',
    client: 'Acme Corp',
    commodity: 'Crude Oil (Brent)',
    supplier: 'Saudi Aramco',
    quantity: '5,000 bbls',
    vesselName: 'MT Arabian Breeze',
    vesselStatus: 'In Transit',
    departure: '2025-05-25',
    eta: '2025-06-15',
    documentStatus: 'Complete',
    lc_status: 'Confirmed',
  },
  {
    shipmentId: 'SHIP-2025-002',
    client: 'Asian Metals Corp',
    commodity: 'Iron Ore (62% Fe)',
    supplier: 'Vale Brazil',
    quantity: '50,000 MT',
    vesselName: 'Bulk Carrier Fortuna',
    vesselStatus: 'At Port - Loading',
    departure: '2025-06-05',
    eta: '2025-07-20',
    documentStatus: 'In Progress',
    lc_status: 'Pending',
  },
  {
    shipmentId: 'SHIP-2025-003',
    client: 'Global Energy Solutions',
    commodity: 'Natural Gas (LNG)',
    supplier: 'Qatar Petroleum',
    quantity: '1,000 MMBtu',
    vesselName: 'LNG Carrier Doha Explorer',
    vesselStatus: 'At Loading Terminal',
    departure: '2025-06-08',
    eta: '2025-06-28',
    documentStatus: 'Complete',
    lc_status: 'Confirmed',
  },
  {
    shipmentId: 'SHIP-2025-004',
    client: 'European Industrial Group',
    commodity: 'Coal (Thermal)',
    supplier: 'Indonesian Mining',
    quantity: '100,000 MT',
    vesselName: 'Bulk Carrier Supreme',
    vesselStatus: 'Scheduled',
    departure: '2025-07-01',
    eta: '2025-08-10',
    documentStatus: 'Pending',
    lc_status: 'Review',
  },
  {
    shipmentId: 'SHIP-2025-005',
    client: 'Pacific Trade Partners',
    commodity: 'Copper (Grade A)',
    supplier: 'Peru Copper Mining',
    quantity: '250 MT',
    vesselName: 'Container Ship Pacific',
    vesselStatus: 'In Transit',
    departure: '2025-06-01',
    eta: '2025-06-22',
    documentStatus: 'Complete',
    lc_status: 'Confirmed',
  },
  {
    shipmentId: 'SHIP-2025-006',
    client: 'Middle East Resources',
    commodity: 'Crude Oil (WTI)',
    supplier: 'US Energy Corp',
    quantity: '20,000 bbls',
    vesselName: 'MT Gulf Stream',
    vesselStatus: 'Delivered',
    departure: '2025-05-10',
    eta: '2025-05-30',
    documentStatus: 'Complete',
    lc_status: 'Settled',
  },
];

export const MOCK_KYC_KYB_REQUESTS = [
  {
    id: 'KYC-2026-001',
    companyName: 'Atlas Refining Pte Ltd',
    email: 'ops@atlasrefining.sg',
    entityType: 'KYC',
    submittedAt: '2026-06-01',
    riskLevel: 'Medium',
    status: 'Pending Review',
  },
  {
    id: 'KYB-2026-002',
    companyName: 'Helios Mineral Resources',
    email: 'legal@heliosminerals.com',
    entityType: 'KYB',
    submittedAt: '2026-06-02',
    riskLevel: 'Low',
    status: 'Pending Review',
  },
];
